### ISSUE TITLE
CTkButton text alignment

### ISSUE THREAD

**Issue by austrianadrian** [TomSchimansky/CustomTkinter#376] opened 2022-08-09 19:10 UTC
Hi there!
is there a solution, if I want to set the text and image alignment in the button on the left or right side ?

**Comment by TheFallen-Cat** [comment] 2022-08-10 11:20
Yes, in order to place the image on right or left you can use the argument `compound="right"/"left"`

**Comment by austrianadrian** [comment] 2022-08-10 11:33
ok.. sorry.. I didn't mean the compound.. I mean the "justify" or "alignment" of both elements in the button element.. 
example:
Situation now:
|****image**TEXT****|

what I want:
|*image**TEXT****|
the alignment of both should be on the left.. 
or right..

**Comment by austrianadrian** [comment] 2022-08-10 11:36
![Bildschirmfoto 2022-08-10 um 13 36 38](https://user-images.githubusercontent.com/110934483/183891752-9091fd02-1865-4320-b30c-d8263e47cf1c.png)

**Comment by austrianadrian** [comment] 2022-08-10 11:37
so there is my optic problem...

**Comment by TheFallen-Cat** [comment] 2022-08-10 16:22
Ok, so you want the images to stick to the left side, no matter how long the text is?

**Comment by austrianadrian** [comment] 2022-08-10 16:43
the images and the text .. 
like the following picture..

**Comment by austrianadrian** [comment] 2022-08-10 16:46
![Bildschirmfoto 2022-08-10 um 18 43 30](https://user-images.githubusercontent.com/110934483/183966955-469c6d29-1522-4cdd-9a25-240f2f49b720.png)

**Comment by TomSchimansky** [comment] 2022-08-11 20:07
I will add this feature next week when I have time!

austrianadrian ***@***.***> schrieb am Mi., 10. Aug. 2022
18:46:

**Comment by austrianadrian** [comment] 2022-08-12 00:26
😍

**Comment by TomSchimansky** [comment] 2022-08-16 18:25
Duplicate of https://github.com/TomSchimansky/CustomTkinter/issues/164

**Closed by TomSchimansky** 2022-08-16 18:25 UTC
Labels: duplicate, enhancement
