### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils' with Python 3.12

### ISSUE THREAD

**Issue by wrogner** [TomSchimansky/CustomTkinter#2023] opened 2023-10-09 12:41 UTC
No module distutils in Python 3.12 makes CustomTkinter traceback:

```
Traceback (most recent call last):
  File "/Users/wolf/Development/py/9 projects/AVScanner/src/AVScanner/ui/avscanner_ui.py", line 16, in <module>
    from customtkinter import (CTk, CTkFrame, CTkLabel, CTkButton, CTkImage, CTkFont, set_appearance_mode)
  File "/Users/wolf/Development/py/9 projects/AVScanner/venv/lib/python3.12/site-packages/customtkinter/__init__.py", line 10, in <module>
    from .windows.widgets.appearance_mode import AppearanceModeTracker
  File "/Users/wolf/Development/py/9 projects/AVScanner/venv/lib/python3.12/site-packages/customtkinter/windows/__init__.py", line 1, in <module>
    from .ctk_tk import CTk
  File "/Users/wolf/Development/py/9 projects/AVScanner/venv/lib/python3.12/site-packages/customtkinter/windows/ctk_tk.py", line 2, in <module>
    from distutils.version import StrictVersion as Version
ModuleNotFoundError: No module named 'distutils'
```

See: [PEP 632 – Deprecate distutils module](https://peps.python.org/pep-0632/)

Also (using StrictVersion from distutils):

DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

(similar to #2022)

**Comment by wrogner** [comment] 2023-10-09 13:01
Sorry: Reinstalled both 3.11 and 3.12 virtual environments (venv) -> No error messages appear. -> App works.
Nevertheless: the dependency from distutils need be eliminated.

**Comment by TechPro424** [comment] 2023-10-14 16:38
Having the same issue, am not using venvs

**Comment by insolor** [comment] 2023-10-16 06:01
@TechPro424 this is not related to venvs, CustomTkinter simply doesn't support Python 3.12 yet.

**Comment by wrogner** [comment] 2023-10-16 06:39
If you don't want to accept @insolor 's suggestion of downgrading (for whatever reason):

- If you don't use a venv, do (that way you isolate the issue to plain Python 3.12 and CustomTkinter).
- Install fresh with 3.12, customtkinter and setuptools
- Test a simple window (e.g. https://customtkinter.tomschimansky.com/tutorial/grid-system, which already passes the StrictVersion check). 
- If this works, fine, if not, provide traces.

Regarding "waiting half a year":
- Adopting new versions is not a question of delay but rather of requirements, thorough testing and careful evaluation.
- Any platform requires knowledgable early adopters to improve and mature.
- Waiting without analysis provides no additional benefit.

**Comment by insolor** [comment] 2023-10-16 07:06
After some investigation (ideas of a pull request):

- It's necessary to add [`packaging`](https://pypi.org/project/packaging/) dependency (needs at least Python 3.7, the same minimal version as CustomTkinter needs)
- in https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/windows/ctk_tk.py replace `from distutils.version import StrictVersion as Version` with `from packagin.version import parse` (source: https://github.com/pypa/setuptools/discussions/3145#discussioncomment-4338944)  
   (or `from packagin.version import parse as parse_version` for better code readability)  
- Replace `Version(...)` with `parse(...)` (or `parse_version(...)`) in ctk_tk.py

**Comment by wrogner** [comment] 2023-10-16 07:51
@insolor : thanks

In CustomTkinter/customtkinter/windows/ctk_tk.py:

replace:

> from distutils.version import StrictVersion as Version

with:

> from packaging.version import parse as Version

I have to test that a little more, but it seems to work.

**Comment by wrogner** [comment] 2023-10-16 09:06
@insolor 
From a programming point of view, I fully agree.
For a quick fix, I think, this would be fastest.

**Comment by TechPro424** [comment] 2023-10-16 11:26
I ended up using a venv, and you were right: the issue is that CTK dies not support 3.12.

**Comment by TomSchimansky** [comment] 2023-10-17 08:51
duplicate of #2005

**Closed by TomSchimansky** 2023-10-17 08:51 UTC
Labels: duplicate
