### ISSUE TITLE
round Button with a white border

### ISSUE THREAD

**Issue by Sinexo** [TomSchimansky/CustomTkinter#2021] opened 2023-10-08 17:25 UTC
Hi,
I am trying to use a round button, but everything I try has a white border like this
![image](https://github.com/TomSchimansky/CustomTkinter/assets/61741553/d7ce2c8d-5c87-4887-ba27-9689d5c45b6a)
I don't know what to change now.
Here is my code 

```
button_1 = customtkinter.CTkButton(
    master=window,
    
    text="Déverouiller",  
    font=("Poppins Medium", 14, "bold"),  
    width=405,
    height=35,
    command=lambda: print("button_1 clicked"),
    fg_color="#D694DC",  
    corner_radius=10,
    border_spacing=-1,
    border_width=-1,
    border_color=("-transparentcolor", "white")
    
)

button_1.place(x=87.0, y=324.0)
```

**Comment by Akascape** [comment] 2023-10-11 08:32
@Sinexo Duplicate of https://github.com/TomSchimansky/CustomTkinter/issues/1377

**Closed** 2023-10-17 08:17 UTC
