### ISSUE TITLE
how to use font from `.ttf` file

### ISSUE THREAD

**Issue by Sayad-Uddin-Tahsin** [TomSchimansky/CustomTkinter#2354] opened 2024-04-04 07:23 UTC
Is there any way to use a Custom Font by importing from a `.ttf` file in CustomTkinter?

**Comment by Akascape** [comment] 2024-04-05 07:35
@Sayad-Uddin-Tahsin Duplicate of #900

**Comment by Akascape** [comment] 2024-04-05 14:31
@Sayad-Uddin-Tahsin 
Check this: https://github.com/TomSchimansky/CustomTkinter/discussions/900#discussioncomment-8954115

**Closed** 2024-04-15 13:58 UTC
