### ISSUE TITLE
Top level widget fails to close if an error occurs

### ISSUE THREAD

**Issue by correa-coder** [TomSchimansky/CustomTkinter#205] opened 2022-06-24 00:22 UTC
Hey, Tom! I'm liking the custom tkinter library, you're doing an amazing job on this project, but today I found a bug and I want to notify you about it.

**Description of the bug:**

If there's an error in a widget that's in a customtkinter.CTkToplevel() like a Label with `font` parameter instead of `text_font` for instance, it will freeze the top-level widget when you click to close it and it will also output the following message to the terminal:

![ctk_bug](https://user-images.githubusercontent.com/80556636/175435466-40327be3-a59c-4f16-8186-46b3b2328682.png)

&rarr; The only way to close it is by killing the process

The source code of the script from the screenshot is the following:
```python
import tkinter
import customtkinter

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("blue")

app = customtkinter.CTk()
app.geometry("400x240")

def button_function():
    # TOP LEVEL
    window = customtkinter.CTkToplevel(app)

    customtkinter.CTkLabel(window, text="You can't close this top level window!").pack()

    """
    This will cause a bug that prevents to close the top level window because there's a wrong property (font instead of text_font) but any other error that occurs will prevent the top level from closing.
    """
    customtkinter.CTkButton(window, text="Click", font=('Arial', 12))

button = customtkinter.CTkButton(master=app, text="CTkButton", command=button_function)
button.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

app.mainloop()
```

**Comment by felipetesc** [comment] 2022-06-24 02:07
I have the same result described by  [correa-coder](https://github.com/correa-coder)

I added the code bellow on my cloned rep, it was placed before calling super inside ctk_button and it works. I think the problem is related how ctk uses text_font and how tkinter treats font. Maybe they have a different configuration.

```python
if "font" in kwargs :
            self.text_font = kwargs["font"]
            del kwargs["font"]
            print("font in kwargs")
        if "font" in args:
            self.text_font = args["font"]
            del args["font"]
            print("font in args")
```

To test I changed [correa-coder](https://github.com/correa-coder) code a litle bit:

```python
from functools import partial
from distutils.cmd import Command

import tkinter
import customtkinter

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("blue")

app = customtkinter.CTk()
app.geometry("400x240")

def close_this(ref):
    ref.destroy()


def button_function():
    # TOP LEVEL
    window = customtkinter.CTkToplevel(app)

    customtkinter.CTkLabel(window, text="You can't close this top level window!").pack()

    """
    This will cause a bug that prevents to close the top level window because there's a 
    wrong property (font instead of text_font) but any other error that occurs will prevent 
    the top level from closing.
    """

    customtkinter.CTkButton(window, text="Click", command = partial(close_this, window), text_font=('Arial', 12)).pack()

button = customtkinter.CTkButton(master=app, text="CTkButton", command=button_function)
button.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

app.mainloop()
```
Hope it helps

**Comment by felipetesc** [comment] 2022-06-24 02:32
I used your code and the same happens with me.

I added this code inside widget_base_class to test:

```python

if "font" in kwargs :
            del kwargs["font"]
            print("font deleted before passing it to tkinter.Frame")
        print("hello before super")
```
and after that it worked.


I changed your code slightly to this:

```python
from functools import partial
from distutils.cmd import Command
import sys
sys.path.append("/run/media/ftx/HD1T/Repositories/Github/CustomTkinter/")

import tkinter
import customtkinter

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("blue")

app = customtkinter.CTk()
app.geometry("400x240")

def close_this(ref):
    ref.destroy()


def button_function():
    # TOP LEVEL
    window = customtkinter.CTkToplevel(app)

    customtkinter.CTkLabel(window, text="You can't close this top level window!").pack()

    """
    This will cause a bug that prevents to close the top level window because there's a 
    wrong property (font instead of text_font) but any other error that occurs will prevent 
    the top level from closing.
    """

    customtkinter.CTkButton(window, text="Click", command = partial(close_this, window), font=('Arial', 12) ).pack()

button = customtkinter.CTkButton(master=app, text="CTkButton", command=button_function)
button.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

app.mainloop()
```
I'm guessing we can't just pass kwargs using inheritance without checking its inner values, and it means we need to verify every widget and remove unused parameters.

**Comment by TomSchimansky** [comment] 2022-06-24 16:29
Ok, I can catch this error, maybe this is helpful for debugging...

**Comment by correa-coder** [comment] 2022-06-24 16:33
After reading the traceback again I noticed the exception is coming from the `remove` method from the `AppearanceModeTracker` class, so maybe the fix should be done there

**Comment by felipetesc** [comment] 2022-06-24 21:35
As temporary workaround, I included inside widget_base_class the code: 

```python
def super_kwargs_checker(parent_kwargs, child_kwargs):
    new_kwargs = dict()
    for child_key in child_kwargs:
        if hasattr(parent_kwargs, child_key) :
            new_kwargs[child_key] = child_kwargs.get(child_key)
    return new_kwargs
```
and inside the method:


```python
def __init__(self,
                 *args,
                 bg_color: Union[str, tuple] = None,
                 width: int,
                 height: int,
                 **kwargs):
```

and I changed super call to this:

```python
super().__init__(*args, width=width, height=height, **super_kwargs_checker(super, kwargs))  # set desired size of underlying tkinter.Frame

```

**Comment by TomSchimansky** [comment] 2022-06-25 20:41
I just added a try except to the remove function in the appearance mode tracker like this, and the error does not appear any more:
```python
    @classmethod
    def remove(cls, callback: Callable):
        try:
            cls.callback_list.remove(callback)
        except ValueError:
            return
```

**Comment by TomSchimansky** [comment] 2022-06-28 09:44
I uploaded version 4.5.1 now and this should be fixed.

**Closed by TomSchimansky** 2022-06-28 09:44 UTC
Labels: enhancement
