### ISSUE TITLE
Removing border in slider widget

### ISSUE THREAD

**Issue by IshanJ25** [TomSchimansky/CustomTkinter#21] opened 2021-12-23 17:43 UTC
![image](https://user-images.githubusercontent.com/86649457/147275185-1beab06a-8076-4010-82ca-b59d1c2c5feb.png)

I am unable to remove this border.
I edited some code to get `.configure` method for slider widget, and when I call this method, this thick border forms around the slider widget. How to remove this?

@jaivardhan-bhola

**Comment by TomSchimansky** [comment] 2021-12-23 17:53
So you want to remove the white border around the slider? When you create the Slider with no arguments at all there is no border because the border_color argument is None by default and so the border_color is the color of the frame behind the slider. And when the slider gets a white border when you call your configure method, then you set the border_color to white in your configure method. But I can't do anything without seeing your code.

**Comment by IshanJ25** [comment] 2021-12-24 10:56
here is the code:

![image](https://user-images.githubusercontent.com/86649457/147346892-797d4a11-3123-4448-be81-59226f7b02de.png)
![image](https://user-images.githubusercontent.com/86649457/147346890-f32bde26-4cb1-474e-86cd-c8a6213513b0.png)
![image](https://user-images.githubusercontent.com/86649457/147346893-8c2bf959-776b-4598-a6bf-946238f56dcd.png)

**Comment by IshanJ25** [comment] 2021-12-25 04:51
Any update?

**Comment by TomSchimansky** [comment] 2021-12-26 19:29
I have no idea why youre getting a white border, just use the Slider as it is currently on Github, then there shouldn't be a change of the border color, it has a config function now.

**Comment by IshanJ25** [comment] 2021-12-28 07:35
still same. no change

**Comment by TomSchimansky** [comment] 2022-01-02 14:38
If you still have problems you can .zip your whole project and add it to your comment, so I can run it myself, otherwise I will close this issue because its not reproducible for me.

**Comment by IshanJ25** [comment] 2022-01-03 06:09
here is the repo
https://github.com/IshanJ25/my_color_picker

**Comment by TomSchimansky** [comment] 2022-01-05 22:28
Hey, now I know what's the problem, its a missing feature in the library that is needed for changing the background object (frame) of any CTk object manually. I will add this in the next days. For a quick fix you could also set the border color, what is currently the white border, to your frame color (`border_color=color['main']`). But with the fix it should just work without this.

**Comment by IshanJ25** [comment] 2022-01-12 17:06
I have tried this: `border_color=color['main']`, No effect, still same

**Comment by TomSchimansky** [comment] 2022-01-14 20:25
Just download the current repository, it should work.

**Comment by IshanJ25** [comment] 2022-01-15 10:20
do you suggest that I edit the latest version by adding these lines?

```
    def config(self, *args, **kwargs):
        self.configure(*args, **kwargs)

    def configure(self, *args, **kwargs):
        require_redraw = False  # some attribute changes require a call of self.draw() at the end

        if "fg_color" in kwargs:
            self.fg_color = kwargs["fg_color"]
            require_redraw = True
            del kwargs["fg_color"]

        if "bg_color" in kwargs:
            if kwargs["bg_color"] is None:
                self.bg_color = self.detect_color_of_master()
            else:
                self.bg_color = kwargs["bg_color"]
            require_redraw = True
            del kwargs["bg_color"]

        if "progress_color" in kwargs:
            self.progress_color = kwargs["progress_color"]
            require_redraw = True
            del kwargs["progress_color"]

        if "button_color" in kwargs:
            self.button_color = kwargs["button_color"]
            require_redraw = True
            del kwargs["button_color"]

        if "button_hover_color" in kwargs:
            self.button_hover_color = kwargs["button_hover_color"]
            require_redraw = True
            del kwargs["button_hover_color"]

        if "border_color" in kwargs:
            self.border_color = kwargs["border_color"]
            require_redraw = True
            del kwargs["border_color"]

        if "border_width" in kwargs:
            self.border_width = kwargs["border_width"]
            require_redraw = True
            del kwargs["border_width"]

        if "from_" in kwargs:
            self.from_ = kwargs["from_"]
            require_redraw = True
            del kwargs["from_"]

        if "to" in kwargs:
            self.to = kwargs["to"]
            require_redraw = True
            del kwargs["to"]

        if "number_of_steps" in kwargs:
            self.number_of_steps = kwargs["number_of_steps"]
            require_redraw = True
            del kwargs["number_of_steps"]

        if "command" in kwargs:
            self.callback_function = kwargs["command"]
            require_redraw = True
            del kwargs["command"]

        super().configure(*args, **kwargs)

        if require_redraw:
            self.draw()
```

**Comment by TomSchimansky** [comment] 2022-01-15 22:45
You don't need to edit anything the problem that the border color remains the same as it was initially (white) is fixed in the current Github version.

**Closed by TomSchimansky** 2022-01-15 22:46 UTC
Labels: question

**Comment by TomSchimansky** [comment] 2022-01-15 23:26
Just as a tip you could use a CTkLabel and a CTkEntry for the objects marked in red. Then the text would be centered and the entry would look clean. Otherwise the program looks really good!

<img width="712" alt="Bildschirmfoto 2022-01-16 um 00 23 34" src="https://user-images.githubusercontent.com/66446067/149640933-f2e829c1-fff9-4b6f-a491-41a5e8087691.png">

**Comment by IshanJ25** [comment] 2022-01-16 18:29
Thanks
I just used classic tkinter entry on CTK frame because as you mentioned here: https://github.com/TomSchimansky/CustomTkinter/issues/17#issuecomment-993897800 the text variable parameter is not available yet. I will surely implement CTK entry and label once they get text variable implementation

**Comment by TomSchimansky** [comment] 2022-01-16 18:50
Ahh okay, tkinter variables are actually there for all widgets since today in the Github version.

And because of the antialiasing on windows I already did a lot of research and it seems like its not possible with the normal tkinter canvas. A solution would be to use this (https://web.archive.org/web/20200619012602id_/http://effbot.org/zone/pythondoc-aggdraw.htm) for drawing, which is compatible with tkinter, but it looks like you cannot reference specific objects on the canvas, just draw on top or clear the whole canvas. Maybe I will try to render the widgets with this library on Windows...

**Comment by IshanJ25** [comment] 2022-01-17 17:12
okay thanks
