### ISSUE TITLE
Need for hereditary feature that was in classic tkinter. The Treeview

### ISSUE THREAD

**Issue by emircetinmemis** [TomSchimansky/CustomTkinter#1680] opened 2023-05-31 21:58 UTC
#### Hi, I have been searching about UI frameworks for tkinter, and found out the most accurate one was customtkinter for me. I was about to turn my application to customtkinter, but I realized that I'm facing with a problem on a specific widget. My application uses several tables or lists on displaying purposes. So with this, I must be able to use a widget like Treeview which comes from the culture of tkinker.

* The mentioned widget call
> ttk.Treeview

##### An example of a basic execution;

```python
from 	tkinter 		import ttk
import 	customtkinter 	as ctk
import 	tkinter 		as tk

class WithNormalTk(tk.Tk) :
    
  def __init__(self, *args, **kwargs) :
    super().__init__(*args, **kwargs)

    treeview = ttk.Treeview(self, height=4, show="headings", selectmode="browse")
    treeview.pack(side="top", fill="both", expand=True)

    treeview["columns"] = ("one", "two", "three")

    treeview.heading("one", text="Column A")
    treeview.heading("two", text="Column B")
    treeview.heading("three", text="Column C")

    treeview.column("one", width=100)
    treeview.column("two", width=100)
    treeview.column("three", width=100)

    treeview.insert("", "end", values=("1", "2", "3"))
    treeview.insert("", "end", values=("4", "5", "6"))
    treeview.insert("", "end", values=("7", "8", "9"))

class WithCustomTk(ctk.CTk) :

  def __init__(self, *args, **kwargs) :
    super().__init__(*args, **kwargs)

    # TODO: Find a way out.

if __name__ == "__main__" :
  
  app = WithNormalTk()
  app.mainloop()

  app = WithCustomTk()
  app.mainloop()
```

##### And this shortly results as;

![1](https://github.com/TomSchimansky/CustomTkinter/assets/82613491/6284df79-1faa-4549-9200-1105eb19b1d4)
![2](https://github.com/TomSchimansky/CustomTkinter/assets/82613491/c2bdda53-7840-441f-9bbe-58bccc283c96)

##### What I have tried to do;

* I have tried to use the scrollable frame that you have done. It kinda worked, but not it was seem to be understandable that, that widget was not supposed to look like that or stay like that. And also the second case with the scrollable frame problem was the core functionalies served by treeview, with a couple of binding I was almost able to reach whatever I want inside that table, but it is not the case with scrollable frame.

##### The solution;

* Treeview like widget should be added.

**Comment by emircetinmemis** [comment] 2023-05-31 22:05
> I forgat too add this.

#### For the "What I have tried to do;" part,
* I also tried to mix things up by using CTk widgets with ttk.Treeview by setting up this `ctk.deactivate_automatic_dpi_awareness()` And again as I said before, It doesn't just look like what ,it actually should look like.

**Comment by TomSchimansky** [comment] 2023-06-15 11:54
You can still use a tkinter treevieew in CustomTkinter:
```python
from tkinter import ttk
import customtkinter


class WithCustomTk(customtkinter.CTk):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.grid_columnconfigure(0, weight=1)

        self.font = customtkinter.CTkFont("Arial", 18)

        self.treeview_heading_style = ttk.Style(self)
        self.treeview_heading_style.theme_use("clam")
        self.treeview_heading_style.configure("Treeview.Heading", background="black", foreground="white",
                                              highlightthickness=0, bd=0, font=self.font)

        self.treeview_style = ttk.Style(self)
        self.treeview_style.theme_use("clam")
        self.treeview_style.configure("Treeview", background="black", foreground="white",
                                      highlightthickness=0, bd=0, font=self.font)

        self.treeview = ttk.Treeview(self, height=4, show="headings", selectmode="browse")
        self.treeview.grid(row=0, column=0, sticky="nsew")

        self.treeview["columns"] = ("one", "two", "three")

        self.treeview.heading("one", text="Column A")
        self.treeview.heading("two", text="Column B")
        self.treeview.heading("three", text="Column C")

        self.treeview.column("one", width=100)
        self.treeview.column("two", width=100)
        self.treeview.column("three", width=100)

        self.treeview.insert("", "end", values=("1", "2", "3"))
        self.treeview.insert("", "end", values=("4", "5", "6"))
        self.treeview.insert("", "end", values=("7", "8", "9"))


if __name__ == "__main__":
    app = WithCustomTk()
    app.mainloop()
```

<img width="628" alt="Bildschirm­foto 2023-06-15 um 13 54 10" src="https://github.com/TomSchimansky/CustomTkinter/assets/66446067/b9082a88-7531-4fb7-8081-2c4d04e11746">

**Comment by TomSchimansky** [comment] 2023-06-15 11:55
Duplicate of https://github.com/TomSchimansky/CustomTkinter/issues/1187

**Closed by TomSchimansky** 2023-06-15 11:54 UTC
