### ISSUE TITLE
What do I use in place of `ttk.Labelframe`?

### ISSUE THREAD

**Issue by demberto** [TomSchimansky/CustomTkinter#29] opened 2022-02-13 11:45 UTC
Since I can't just directly embed a `CTkEntry` in a normal `ttk.Labelframe` (see error below)

```none
Traceback (most recent call last):
    main()
    App().mainloop()
    self.ob = ctk.CTkEntry(og)
  File "site-packages\customtkinter\customtkinter_entry.py", line 54, in __init__
    self.bg_color = self.detect_color_of_master() if bg_color is None else bg_color
  File "site-packages\customtkinter\customtkinter_entry.py", line 119, in detect_color_of_master
    return self.master.cget("bg")
  File "Python39\lib\tkinter\__init__.py", line 1652, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
_tkinter.TclError: unknown option "-bg"
```

What should be the replacement be?

**Comment by demberto** [comment] 2022-02-13 19:21
Its a bug? Tkinter sure as hell has a lot of bugs to be called stable and mature

**Comment by TomSchimansky** [comment] 2022-04-10 21:09
So the CTk widgets now work on ttk.Frame, ttk.LabelFrame and ttk.Notebook. But only with the default color:

![Bildschirmfoto 2022-04-10 um 23 00 46](https://user-images.githubusercontent.com/66446067/162639799-ba2cbb12-835b-401c-b987-57a135cde175.png)
Program: `test/test_ttk_frames.py`

If the color gets changed by a ttk style, then you have to manually set the `bg_color` attribute of all CTk widgets on them to the new color, it's not possible to do this automatically for me at the moment.

But overall it would prefer to use a CTkFrame instead of a ttk.Labelframe because it's more convenient and you can also place a label at the top as I did in `test/test_ttk_frames.py` and add a border if you want.

**Comment by sumeshir26** [comment] 2022-04-11 13:40
bg_color = tkinter.ttk.Style().lookup(".", "background")

**Comment by TomSchimansky** [comment] 2022-04-11 13:53
I now, actually, what I do to get the bg color of the master widget is this on ttk widgets:
```python
ttk_style = ttk.Style()
return ttk_style.lookup(self.master.winfo_class(), 'background')
```
`customtkinter/widgets/customtkinter_button.py line 144`

The problem is, that I cannot now if the style gets changed afterwards in the runtime of the program. Then I would have to change the bg_color of the ctk button again. On tkinter widgets, I do this by overwriting the configure method of the master, so that all the ctk childs on that master get notified when the bg color of the master gets configured. But with ttk i can't do this, because the bg change of the master doesn't happen through the configure method, but a style change. And there is nothing like a style change event or something similar.

**Comment by demberto** [comment] 2022-04-11 18:20
> And there is nothing like a style change event

There is `<<ThemeChanged>>`, although I am not sure you need it.

**Comment by TomSchimansky** [comment] 2022-04-15 17:48
ThemeChanged only gets called if you load a new theme, but there is no event for individual theme modifications on widgets, so I will close this one.

**Closed by TomSchimansky** 2022-04-15 17:48 UTC
Labels: bug

**Comment by demberto** [comment] 2022-04-16 11:45
@TomSchimansky There's also `<Configure>` *maybe* that's what you are looking for?
