### ISSUE TITLE
Add custom titlebar

### ISSUE THREAD

**Issue by lorypelli** [TomSchimansky/CustomTkinter#1687] opened 2023-06-03 10:24 UTC
Actually, there is a way to replace windows default titlebar with a custom one, it will be good, if it's adaptive with the theme (light or dark)

**Comment by Akascape** [comment] 2023-06-04 14:50
If you are on windows 11, here is the technique to change title bar colors: https://github.com/TomSchimansky/CustomTkinter/discussions/1299

If you are loonking for a custom title bar, check this: https://github.com/Akascape/CTkMenuBar

**Comment by Akascape** [comment] 2023-06-04 17:20
@lorypelli

**Comment by dishb** [comment] 2023-06-13 23:21
@lorypelli - CTk's menubars are already adaptive to light/dark modes on both Windows and macOS. Just wanted to point that out - I understand you're looking for a _custom_ menubar/titlebar.

**Comment by lorypelli** [comment] 2023-06-14 06:24
> @lorypelli - CTk's menubars are already adaptive to light/dark modes on both Windows and macOS. Just wanted to point that out - I understand you're looking for a _custom_ menubar/titlebar.

I said custom titlebar because I want it adaptive, are menubars the same?

**Comment by dishb** [comment] 2023-06-14 21:13
@lorypelli - I apologize, I've added more confusion to this! 😅 . Menubars and titlebars are different things.

**Comment by lorypelli** [comment] 2023-06-15 05:41
> @lorypelli - I apologize, I've added more confusion to this! 😅 . Menubars and titlebars are different things.
> 
> Looking at #1299 will answer your question (as @Akascape originally posted).
> 
> Please close this issue if the above works for you.

I need it for win 10

**Comment by TomSchimansky** [comment] 2023-06-15 10:57
@lorypelli do you mean you want to change the color of the titlebar?

**Comment by lorypelli** [comment] 2023-06-15 11:00
> @lorypelli do you mean you want to change the color of the titlebar?

Yes

**Comment by Akascape** [comment] 2023-06-15 13:22
@lorypelli All DWM attributes are not implemented in windows 10 so there is no way to change it. But on windows 11, it change be changed using the last method given on #1299.
However, this method will work on windows 10 but will change the whole accent of the application:
```python
import customtkinter
from ctypes import POINTER, pointer, sizeof, windll, Structure, byref, c_int
from ctypes.wintypes import DWORD, ULONG


class ACCENT_POLICY(Structure):
        _fields_ = [
            ('AccentState',   DWORD),
            ('AccentFlags',   DWORD),
            ('GradientColor', DWORD),
            ('AnimationId',   DWORD),
        ]

class WINDOW_COMPOSITION_ATTRIBUTES(Structure):
        _fields_ = [
            ('Attribute',  DWORD),
            ('Data',       POINTER(ACCENT_POLICY)),
            ('SizeOfData', ULONG),
        ]

def ChangeAccent(hWnd: int, Color):
                                    
        accentPolicy = ACCENT_POLICY()  
                                    
        winCompAttrData = WINDOW_COMPOSITION_ATTRIBUTES()
        winCompAttrData.Attribute = 19 # also try 30
        winCompAttrData.SizeOfData = sizeof(accentPolicy)
        winCompAttrData.Data = pointer(accentPolicy)

        accentPolicy.AccentState = 1
        accentPolicy.GradientColor = Color
                        
        windll.user32.SetWindowCompositionAttribute(hWnd, pointer(winCompAttrData))
                        
root = customtkinter.CTk()

HWND = windll.user32.GetParent(root.winfo_id())
color = 0xFF0000 # rgb order: 0xbbggrr
ChangeAccent(HWND, color)

root.mainloop()
```
**If you are trying to just replace the black color title bar of Dark Mode then just use ` winCompAttrData.Attribute = 30`.**

**Comment by TomSchimansky** [comment] 2023-06-15 19:57
duplicate of https://github.com/TomSchimansky/CustomTkinter/discussions/1299#discussioncomment-6186664

**Closed** 2023-06-15 19:56 UTC
Labels: question
