### ISSUE TITLE
Scrollable Frame issue (AttributeError)

### ISSUE THREAD

**Issue by nikita276956** [TomSchimansky/CustomTkinter#1253] opened 2023-02-20 14:03 UTC
when I try to use CTkScrollableFrame
it types: AttributeError: module 'customtkinter' has no attribute 'CTkScrollableFrame'

**Comment by ElectricCandlelight** [comment] 2023-02-20 14:31
Possible duplicate of #1232 

Please try upgrading to the latest version

```pip3 install customtkinter --upgrade```

**Comment by nikita276956** [comment] 2023-02-20 16:00
Thanks it worked!

בתאריך יום ב׳, 20 בפבר׳ 2023, 16:31, מאת ElectricCandlelight ‏<
***@***.***>:

**Closed** 2023-02-20 22:48 UTC
