### ISSUE TITLE
Strange looking button with jagged edges

### ISSUE THREAD

**Issue by sigau** [TomSchimansky/CustomTkinter#1620] opened 2023-05-15 13:12 UTC
Dear CustomTkinter team,

First of all, I would like to express my gratitude for providing such a useful tool that has helped me create a modern-looking UI in no time.

However, I have come across a strange issue while adapting my interface using your package. The corners of the buttons and frames are appearing jagged and not rounded as they should be. I have attached two images in the light and dark theme to demonstrate the issue.

Light Theme Image:
![Capture d’écran du 2023-05-15 15-01-26](https://github.com/TomSchimansky/CustomTkinter/assets/44998219/7f01786c-0a5d-4035-9173-a9e6361877d9)
Dark Theme Image: 
![Capture d’écran du 2023-05-15 15-02-11](https://github.com/TomSchimansky/CustomTkinter/assets/44998219/d51123cc-f08d-4ee1-85ce-88255874aca2)

I would appreciate it if you could look into this issue and suggest a possible solution. Thank you in advance for your time and assistance.

I'm using Ubuntu 22.04.2 LTS with python 3.10.10 and customtkinter v5.1.3

Best regards,
Gautier

**Comment by sigau** [comment] 2023-05-15 14:39
Hi,
Sorry for the unnecessary issue I raised earlier. I tried the script on another computer, and it worked perfectly fine. 
Thank you.

**Comment by avalon60** [comment] 2023-05-18 20:26
I don't see that behaviour on Linux Mint. Have you tried reproducing with [simple_example.py](https://github.com/TomSchimansky/CustomTkinter/blob/master/examples/simple_example.py)?

**Comment by Akascape** [comment] 2023-05-20 03:43
This bug is reported several times,  https://github.com/TomSchimansky/CustomTkinter/issues/1384

Idk but to my experience, linux and mac os tkinter are really buggy.

**Comment by avalon60** [comment] 2023-05-20 17:14
There was some speculation as to whether this was something to do with Anaconda. I don't  use Anaconda, or at least haven't done so for some time, and never used it at all for GUI apps. I also use Linux Mint, which is based on Ubuntu and I have never experienced issues like this.

**Comment by sigau** [comment] 2023-05-20 19:29
The bug consistently manifests on both servers/computers where I have installed conda, even when using different Python versions. Unfortunately, I haven't had the chance to try the provided simple_example.py script yet. However, I am committed to testing it later and will retry the experience with my program on the same computer/server but without conda.

Once I have obtained the results, I will make sure to update this GitHub issue accordingly and provide you with the relevant information.

Thank you for your attention to this matter, and I appreciate your efforts in maintaining and improving the program.

**Comment by avalon60** [comment] 2023-05-30 17:16
I just stumbled across, this:

https://github.com/ContinuumIO/anaconda-issues/issues/6833

It's not looking good for Anaconda. It seems it's impacting fonts in Tkinter.

**Comment by sigau** [comment] 2023-06-05 07:19
I'm not sure if this can be considered a definitive "solution," but it has worked for us. Instead of using conda, I deactivated it and created a Python virtual environment. Inside this environment, I installed all the necessary packages required for my script to function properly. When I reactivate conda and then activate the Python environment, everything works without any issues. Although this is only a temporary workaround, it has proven effective for us.

**Comment by dishb** [comment] 2023-06-22 15:04
> It's not looking good for Anaconda. It seems it's impacting fonts in Tkinter.

That would make sense because I think CustomTkinter uses fonts to help render the round corners.

See [this](https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/assets/fonts/CustomTkinter_shapes_font.otf) file.

**Comment by dishb** [comment] 2023-06-22 15:05
@sigau - Close as duplicate of #1384?

**Closed** 2023-06-27 07:28 UTC
