### ISSUE TITLE
Error message after tkinter window is destroyed

### ISSUE THREAD

**Issue by LJDrakeley** [TomSchimansky/CustomTkinter#2283] opened 2024-02-26 15:16 UTC
When closing my custom tkinter window, I receive the following error message: 

invalid command name "2462417235584update"
    while executing
"2462417235584update"
    ("after" script)
invalid command name "2462162051648check_dpi_scaling"
    while executing
"2462162051648check_dpi_scaling"
    ("after" script)

I do not use any custom methods that check for dpi scaling, "update" or any "after" methods. Is this an issue with the package? 
Thank you in advance.

**Comment by LJDrakeley** [comment] 2024-02-27 02:36
Hi Anonymous6598, unfortunately I cannot show the code (and the size of the project is more than 2500 lines long anyway). However, that is the full extent of the error message that occurs when closing the window. I do not have any custom closing method if that helps. If this cannot be resolved without the code it's okay but I'm curious for a solution nonetheless. Thanks!

**Comment by JanPanthera** [comment] 2024-02-27 12:06
Without code its almost impossible to say what's wrong, anyway, the only thing i recommend is, to make sure that your window desrutruction is don properly. Means, if you destroy the window and afterwards try to access something from customtkinter it can lead to an error like this. Hope you find a solution 😸

**Comment by Anonymous6598** [comment] 2024-02-27 17:15
Thanks @JanPanthera for support. Yes, without code it's impossible to understand issue.

**Comment by VillainousSsnake** [comment] 2024-03-10 18:05
I have this exact issue, here is some example code:
```py
import customtkinter as ctk

root = ctk.CTk()

root.mainloop()

root = ctk.CTk()

root.mainloop()
```

**Comment by JanPanthera** [comment] 2024-03-10 18:46
Have you tried to delay the second creation, maybe the internal code is still cleaning up while you are trying to create a new on?

**Comment by VillainousSsnake** [comment] 2024-03-10 18:50
> Have you tried to delay the second creation, maybe the internal code is still cleaning up while you are trying to create a new one?

It still raises this error:
```
invalid command name "2212570062528update"
    while executing
"2212570062528update"
    ("after" script)
```

**Comment by JanPanthera** [comment] 2024-03-10 18:59
yeah thats odd, sorry i don't know, this is something for the actual dev then

**Comment by Anonymous6598** [comment] 2024-03-11 05:57
here is solution to your problem:
```python
import customtkinter as ctk
from time import sleep

root_1 = ctk.CTk()

root_1.protocol("WM_DELETE_WINDOW", root_1.destroy())

root_1.mainloop()

sleep(5)

root_2 = ctk.CTk()

root_2.protocol("WM_DELETE_WINDOW", root_2.destroy())

root_2.mainloop()
```

**Comment by VillainousSsnake** [comment] 2024-03-11 16:46
> ```python
> ```python
> import customtkinter as ctk
> from time import sleep
> 
> root_1 = ctk.CTk()
> 
> root_1.protocol("WM_DELETE_WINDOW", root_1.destroy())
> 
> root_1.mainloop()
> 
> sleep(5)
> 
> root_2 = ctk.CTk()
> 
> root_2.protocol("WM_DELETE_WINDOW", root_2.destroy())
> 
> root_2.mainloop()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
>       
> ```

That doesn't work, this is the error it produces now:
```
Traceback (most recent call last):
  File "C:\Users\username\PycharmProjects\project\TEST.py", line 6, in <module>
    root_1.protocol("WM_DELETE_WINDOW", root_1.destroy())
  File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2253, in wm_protocol
    return self.tk.call(
           ^^^^^^^^^^^^^
_tkinter.TclError: can't invoke "wm" command: application has been destroyed
```

**Comment by FaheemM1020** [comment] 2024-03-12 03:32
> > ```python
> > ```python
> > import customtkinter as ctk
> > from time import sleep
> > 
> > root_1 = ctk.CTk()
> > 
> > root_1.protocol("WM_DELETE_WINDOW", root_1.destroy())
> > 
> > root_1.mainloop()
> > 
> > sleep(5)
> > 
> > root_2 = ctk.CTk()
> > 
> > root_2.protocol("WM_DELETE_WINDOW", root_2.destroy())
> > 
> > root_2.mainloop()
> > ```
> 
> That doesn't work, this is the error it produces now:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\username\PycharmProjects\project\TEST.py", line 6, in <module>
>     root_1.protocol("WM_DELETE_WINDOW", root_1.destroy())
>   File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2253, in wm_protocol
>     return self.tk.call(
>            ^^^^^^^^^^^^^
> _tkinter.TclError: can't invoke "wm" command: application has been destroyed
> ```

Try this :

```
import customtkinter as ctk
from time import sleep

root_1 = ctk.CTk()

root_1.protocol("WM_DELETE_WINDOW", root_1.destroy)

root_1.mainloop()

sleep(5)

root_2 = ctk.CTk()

root_2.protocol("WM_DELETE_WINDOW", root_2.destroy)

root_2.mainloop()
```

**Comment by FaheemM1020** [comment] 2024-03-12 03:34
Try catching with try and except

**Comment by Anonymous6598** [comment] 2024-03-12 11:07
> > > ```python
> > > ```python
> > > import customtkinter as ctk
> > > from time import sleep
> > > 
> > > root_1 = ctk.CTk()
> > > 
> > > root_1.protocol("WM_DELETE_WINDOW", root_1.destroy())
> > > 
> > > root_1.mainloop()
> > > 
> > > sleep(5)
> > > 
> > > root_2 = ctk.CTk()
> > > 
> > > root_2.protocol("WM_DELETE_WINDOW", root_2.destroy())
> > > 
> > > root_2.mainloop()
> > > ```
> > 
> > That doesn't work, this is the error it produces now:
> > 
> > ```
> > Traceback (most recent call last):
> >   File "C:\Users\username\PycharmProjects\project\TEST.py", line 6, in <module>
> >     root_1.protocol("WM_DELETE_WINDOW", root_1.destroy())
> >   File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2253, in wm_protocol
> >     return self.tk.call(
> >            ^^^^^^^^^^^^^
> > _tkinter.TclError: can't invoke "wm" command: application has been destroyed
> > ```
> 
> Try this :
> 
> ```
> import customtkinter as ctk
> from time import sleep
> 
> root_1 = ctk.CTk()
> 
> root_1.protocol("WM_DELETE_WINDOW", root_1.destroy)
> 
> root_1.mainloop()
> 
> sleep(5)
> 
> root_2 = ctk.CTk()
> 
> root_2.protocol("WM_DELETE_WINDOW", root_2.destroy)
> 
> root_2.mainloop()
> ```

You made mistake. `destroy()` is missing. Therefore function won't work.

**Comment by Anonymous6598** [comment] 2024-03-12 21:24
I forgot to put `lambda`
here is solution:
```python
import customtkinter as ctk
from time import sleep

root_1 = ctk.CTk()

root_1.protocol("WM_DELETE_WINDOW", lambda: root_1.destroy())

root_1.mainloop()

root_2 = ctk.CTk()

root_2.protocol("WM_DELETE_WINDOW", lambda: root_2.destroy())

root_2.mainloop()
```

**Comment by VillainousSsnake** [comment] 2024-03-13 16:01
> I forgot to put `lambda` here is solution:
> 
> ```python
> import customtkinter as ctk
> from time import sleep
> 
> root_1 = ctk.CTk()
> 
> root_1.protocol("WM_DELETE_WINDOW", lambda: root_1.destroy())
> 
> root_1.mainloop()
> 
> root_2 = ctk.CTk()
> 
> root_2.protocol("WM_DELETE_WINDOW", lambda: root_2.destroy())
> 
> root_2.mainloop()
> ```

That still produces this error:
```
invalid command name "2742723926720update"
    while executing
"2742723926720update"
    ("after" script)
```

**Comment by VillainousSsnake** [comment] 2024-03-13 16:09
The numbers in the error change every time the program is run for some reason. (Maybe the CTk class has codes for each function??)

**Comment by Anonymous6598** [comment] 2024-03-13 18:06
final solution:
```python
import customtkinter as ctk, sys
from time import sleep

def exit():
    root_1.withdraw()
    
    root_2 = ctk.CTk()

    root_2.protocol("WM_DELETE_WINDOW", lambda: sys.exit())

    root_2.mainloop()

root_1 = ctk.CTk()

root_1.protocol("WM_DELETE_WINDOW", lambda: exit())

root_1.mainloop()


```

**Comment by LJDrakeley** [comment] 2024-03-13 18:31
> Without code its almost impossible to say what's wrong, anyway, the only thing i recommend is, to make sure that your window desrutruction is don properly. Means, if you destroy the window and afterwards try to access something from customtkinter it can lead to an error like this. Hope you find a solution 😸

Understandable! I apologize I cannot give the code, I was hoping it was a more widespread issue that others have commonly seen. Thank you all for your time and efforts. I hope VillainousSsnake finds a solution to their similar issue. It is odd that the window delete protocol must be explicitly stated for correct closing?

**Comment by VillainousSsnake** [comment] 2024-03-13 19:05
> final solution:
> 
> ```python
> import customtkinter as ctk, sys
> from time import sleep
> 
> def exit():
>     root_1.withdraw()
>     
>     root_2 = ctk.CTk()
> 
>     root_2.protocol("WM_DELETE_WINDOW", lambda: sys.exit())
> 
>     root_2.mainloop()
> 
> root_1 = ctk.CTk()
> 
> root_1.protocol("WM_DELETE_WINDOW", lambda: exit())
> 
> root_1.mainloop()
> ```

That works! Thanks for helping me, I was about to put my entire app on hold because of this bug but now I can continue development!

**Comment by Anonymous6598** [comment] 2024-03-13 19:32
Your welcome dude

**Comment by Anonymous6598** [comment] 2024-03-13 19:34
> > Without code its almost impossible to say what's wrong, anyway, the only thing i recommend is, to make sure that your window desrutruction is don properly. Means, if you destroy the window and afterwards try to access something from customtkinter it can lead to an error like this. Hope you find a solution 😸
> 
> Understandable! I apologize I cannot give the code, I was hoping it was a more widespread issue that others have commonly seen. Thank you all for your time and efforts. I hope VillainousSsnake finds a solution to their similar issue. It is odd that the window delete protocol must be explicitly stated for correct closing?

Yes, it is needed.

**Comment by PhilipNelson5** [comment] 2024-03-27 15:49
@LJDrakeley we don't need your entire source code, that would actually be worse. What we need is a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) (MRE). If you can take your application, strip it down to the minimal set of statements that reproduce the bug, then people can use that to diagnose the issue. Without an MRE, any number of things could be causing it.

**Comment by LJDrakeley** [comment] 2024-03-28 19:39
@PhilipNelson5 I have finally been able to track down the issue, as I have just begun a new project and I have come across the same error message. It seems that creating a method that destroys some window, and also creates a new window, is the culprit.

'''

import customtkinter as ctk

class WindowClass(ctk.CTk):
    def __init__(self, parent):
        super().__init__()

        self.parent = parent

        button = ctk.CTkButton(master=self, 
                               text='destroy', 
                               command=lambda: self.parent.open_new_window(self))
        button.pack()


class MainClass:
    def __init__(self):
        window = WindowClass(parent=self)
        window.mainloop()

    def open_new_window(self, some_window):
        some_window.destroy()

        new_window = WindowClass(parent=self)
        new_window.mainloop()


if __name__ == "__main__":
    app = MainClass()

'''

Thanks in advance!

**Comment by LJDrakeley** [comment] 2024-03-28 19:42
@PhilipNelson5 I have finally been able to isolate the problem. I just started a new project and I noticed that by creating a method that destroys some window, and then creates another, causes the error. 

Here is an example: 

```

import customtkinter as ctk

class WindowClass(ctk.CTk):
    def __init__(self, parent):
        super().__init__()

        self.parent = parent

        button = ctk.CTkButton(master=self, 
                               text='destroy', 
                               command=lambda: self.parent.open_new_window(self))
        button.pack()


class MainClass:
    def __init__(self):
        window = WindowClass(parent=self)
        window.mainloop()

    def open_new_window(self, some_window):
        some_window.destroy()

        new_window = WindowClass(parent=self)
        new_window.mainloop()


if __name__ == "__main__":
    app = MainClass()

```

Thanks in advance!

**Comment by PhilipNelson5** [comment] 2024-03-29 16:01
There is a print statement in _\<Python Install Location>/Lib/site-packages/customtkinter/\_\_init\_\_.py:686_ which is part of the `destroy` sequence. Uncommenting it provides some insight. The window is trying to execute commands that have been deleted.

```log
- Tkinter: deleted command 2489637091072_on_enter
- Tkinter: deleted command 2489637091328_on_leave
- Tkinter: deleted command 2489637091584_clicked
- Tkinter: deleted command 2489615068352_on_enter
- Tkinter: deleted command 2489615068800_on_leave
- Tkinter: deleted command 2489615069120_clicked
- Tkinter: deleted command 2489615069632_clicked
- Tkinter: deleted command 2489637089344_update_dimensions_event
- Tkinter: deleted command 2489615088832_click_animation
- Tkinter: deleted command tkerror
- Tkinter: deleted command exit
- Tkinter: deleted command 2489614969856destroy
- Tkinter: deleted command 2489637086144_update_dimensions_event
- Tkinter: deleted command 2489637086400_focus_in_event
- Tkinter: deleted command 2489615069952check_dpi_scaling
- Tkinter: deleted command 2489615057856update
invalid command name "2489615057856update"
    while executing
"2489615057856update"
    ("after" script)
invalid command name "2489615069952check_dpi_scaling"
    while executing
"2489615069952check_dpi_scaling"
    ("after" script)
invalid command name "2489615088832_click_animation"
    while executing
"2489615088832_click_animation"
    ("after" script)
```

**Comment by PhilipNelson5** [comment] 2024-03-29 17:36
I think the problem is creating multiple Tk instances. From what I've read, it can be done, however it is tricky to manage. A simpler path is to create one Tk instance and use multiple TopWindows. Here is a working example:

```python
from typing import Tuple

import customtkinter as CTk


class App(CTk.CTk):
    def __init__(self, fg_color: str | Tuple[str, str] | None = None, **kwargs):
        super().__init__(fg_color, **kwargs)
        self.withdraw()
        self.window = Window(master=self)

    def new_window(self):
        self.window.destroy()
        self.window = Window(master=self)


class Window(CTk.CTkToplevel):
    def __init__(self, master):
        super().__init__(master=master)
        self.geometry("200x80")

        button = CTk.CTkButton(
            master=self,
            text="destroy",
            command=lambda: self.master.new_window(),
        )
        button.pack(padx=25, pady=25)

        self.protocol("WM_DELETE_WINDOW", self.master.destroy)


if __name__ == "__main__":
    app = App()
    app.mainloop()
```

**Comment by LJDrakeley** [comment] 2024-03-29 17:48
Great solution! 

Thank you, I will be implementing this method from now on.

**Comment by PhilipNelson5** [comment] 2024-03-29 17:50
Awesome, if that resolves your problem, you can close this issue.

**Closed** 2024-03-29 17:52 UTC

**Comment by mauripetersen** [comment] 2025-04-05 20:34
@PhilipNelson5, great solution!

Creating only one CTk instance avoids internal conflicts in the Tkinter event loop.
Well done! 👌
