### ISSUE TITLE
Strange glitches in nearly all CTK UI elements on Linux.

### ISSUE THREAD

**Issue by randompast** [TomSchimansky/CustomTkinter#1358] opened 2023-03-17 15:35 UTC
Any example customtkinter code that I try is glitchy.  How do I fix this?  I'm running 20.04 Ubuntu, python 3.8.3, current pip, tk, and ctk.

    import tkinter
    import customtkinter

    customtkinter.set_appearance_mode("System")  # Modes: system (default), light, dark
    customtkinter.set_default_color_theme("blue")  # Themes: blue (default), dark-blue, green

    app = customtkinter.CTk()  # create CTk window like you do with the Tk window

    def button_function():
        print("button pressed")

    # Use CTkButton instead of tkinter Button
    button = customtkinter.CTkButton(master=app, text="CTkButton", command=button_function)
    button.place(relx=0.5, rely=0.5, anchor=tkinter.CENTER)

    app.mainloop()

![image](https://user-images.githubusercontent.com/1652686/225950050-0f11c81e-b1b6-4e93-a9ae-283257851610.png)

**Comment by ElectricCandlelight** [comment] 2023-03-17 16:37
Duplicate of #1271

**Comment by TomSchimansky** [comment] 2023-03-20 21:22
Using anaconda also caused this problem in the past I think.

**Closed by TomSchimansky** 2023-03-20 21:22 UTC

**Comment by CodingLama** [comment] 2024-05-21 11:13
> Duplicate of #1271 upgrade to python 3.10

I am on 3.10 and I am having the same problem.

**Comment by Arritmic** [comment] 2024-11-24 15:56
I confirm that with Python 3.11.9 still having the same issue:

![Screenshot from 2024-11-24 17-55-32](https://github.com/user-attachments/assets/3fd6ecf5-5f5e-4e48-9e6a-a9f557eb78cb)
