### ISSUE TITLE
GUI looks very bad on KDE

### ISSUE THREAD

**Issue by wxguy** [TomSchimansky/CustomTkinter#1400] opened 2023-03-29 16:50 UTC
I am using Arch Linux with a KDE environment. Wanted to try a simple but beautiful Python GUI toolkit and thus landed here. However, to my disappointment, the first example tested using a GUI script downloaded from this repo looks extremely poor. The sample image is attached. Is this intended or can it be improved? 

![custom-tinkter-kde](https://user-images.githubusercontent.com/9054645/228610718-f3e5841f-ac30-4c1e-bc19-e4293da0bde6.png)

I have used the default theme Breeze to check the GUI.

**Comment by ElectricCandlelight** [comment] 2023-03-29 17:08
Duplicate of #1384  #1358 #1271 #931 

Use python version 3..10 / Don't use anaconda.

**Comment by TomSchimansky** [comment] 2023-03-29 22:56
I have no idea why its not working with condo so probably there will be no fix anytime soon.

**Closed by TomSchimansky** 2023-03-29 22:56 UTC
Labels: duplicate
