### ISSUE TITLE
CTkSwitch has no state.

### ISSUE THREAD

**Issue by thomasrgrant** [TomSchimansky/CustomTkinter#95] opened 2022-05-20 18:31 UTC
CTkSwitch has no state.
self.switch_1 = customtkinter.CTkSwitch(master=self,
                                        text_font=('Verdana', 9, 'bold'),
                                        text="Change GUI",
                                        state=tk.DISABLED)
        self.switch_1.place(x=210, y=430)
state does not work.

**Comment by TomSchimansky** [comment] 2022-05-20 18:32
Duplicate of: https://github.com/TomSchimansky/CustomTkinter/issues/43

**Closed** 2022-05-20 18:32 UTC
Labels: duplicate

**Comment by TomSchimansky** [comment] 2022-05-22 18:47
CTkSwitch has now a state attribute which can be configured as of version 4.0.0.
