### ISSUE TITLE
import customtkinter FAILED

### ISSUE THREAD

**Issue by Simoh23999** [TomSchimansky/CustomTkinter#2107] opened 2023-11-25 15:05 UTC
i Install customtkinter and i want to use it , with this basic code cmd return :

Traceback (most recent call last):
  File "C:\Users\hp\Desktop\test\T.py", line 2, in <module>
    import customtkinter
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\customtkinter\__init__.py", line 10, in <module>
    from .windows.widgets.appearance_mode import AppearanceModeTracker
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\customtkinter\windows\__init__.py", line 1, in <module>
    from .ctk_tk import CTk
  File "C:\Users\hp\AppData\Local\Programs\Python\Python312-32\Lib\site-packages\customtkinter\windows\ctk_tk.py", line 7, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
 

`import tkinter
import customtkinter
print("hello world")`

**Comment by Akascape** [comment] 2023-11-26 03:24
@Simoh23999 Install the packaging module first, `pip install packaging`.

**Comment by DerSchinken** [comment] 2023-11-27 14:47
Duplicate of: [Issue #2036](https://github.com/TomSchimansky/CustomTkinter/issues/2036) and will be fixed by [Pull request #2031](https://github.com/TomSchimansky/CustomTkinter/pull/2031)

**Comment by H15STER** [comment] 2023-11-28 10:28
customtkinter not support python 3.12

**Closed** 2023-12-19 23:34 UTC

**Comment by TomSchimansky** [comment] 2024-01-10 02:30
Should be fixed with 5.2.2, as packaging is now added to requirements
