### ISSUE TITLE
CTk 5.1.3: CTkCheckBox has no supporting configure option for checkmark_color

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1703] opened 2023-06-09 12:46 UTC
The CTkCheckBox widget has no supporting configure option for the checkmark_color property, found in the theme files.

Is this accidental?

**Comment by TomSchimansky** [comment] 2023-06-15 10:33
duplicate of https://github.com/TomSchimansky/CustomTkinter/issues/1586, already fixed with commit

**Closed** 2023-06-15 10:33 UTC
Labels: duplicate
