### ISSUE TITLE
Change theme during app running is not working

### ISSUE THREAD

**Issue by learncodingforweb** [TomSchimansky/CustomTkinter#1938] opened 2023-08-24 10:18 UTC
Theme does not change during App running, but if i change theme before app run. Then it works fine.

How to change theme during app running

```
import customtkinter as ttk
import tkinter as tk


class App(ttk.CTk):
    def __init__(self):
        super().__init__()
        self.title("Learn tutorial")
        self.geometry('640x480')

        self.menu=tk.Menu(self, tearoff=False)
        self.config(menu=self.menu)

        self.theme = tk.Menu(self.menu, tearoff=False)
        self.theme.add_command(label='light-blue', command=lambda: self.handler_theme(mode='light', color='blue'))
        self.theme.add_command(label='light-dark-blue', command=lambda: self.handler_theme(mode='light', color='dark-blue'))
        self.theme.add_command(label='light-green', command=lambda: self.handler_theme(mode='light', color='green'))
        self.theme.add_command(label='dark-blue', command=lambda: self.handler_theme(mode='dark', color='blue'))
        self.theme.add_command(label='dark-dark-blue', command=lambda: self.handler_theme(mode='dark', color='dark-blue'))
        self.theme.add_command(label='dark-green', command=lambda: self.handler_theme(mode='dark', color='green'))

        self.menu.add_cascade(label="Mode", menu=self.theme)

        self.lb= ttk.CTkLabel(self, text="home")
        self.btn=ttk.CTkButton(self, text="show")

        self.lb.grid(row=0, column=0)
        self.btn.grid(row=0, column=1)

        self.mainloop()

    def handler_theme(self, mode, color):
        ttk.set_appearance_mode(mode) 
        ttk.set_default_color_theme(color)

    def select_cbx(self, choice):
        print(choice)

    def press(self):
        print("clicked")

if __name__ == "__main__":
    ttk.set_appearance_mode("light")  # Modes: system (default), light, dark
    ttk.set_default_color_theme("green")  # Themes: blue (default), dark-blue, green
    App()
```

**Comment by Akascape** [comment] 2023-08-24 13:02
Another duplicate of https://github.com/TomSchimansky/CustomTkinter/issues/295 https://github.com/TomSchimansky/CustomTkinter/issues/676 https://github.com/TomSchimansky/CustomTkinter/discussions/449 https://github.com/TomSchimansky/CustomTkinter/discussions/1403 https://github.com/TomSchimansky/CustomTkinter/discussions/1824

Short answer: not implemented currently. Make that theme changing option to work after a restart.

**Closed** 2023-08-27 18:15 UTC
Labels: duplicate
