### ISSUE TITLE
CTk V5.1.2: Regression on CTkTopLevel - master keyword now causes exception 

### ISSUE THREAD

**Issue by avalon60** [TomSchimansky/CustomTkinter#1537] opened 2023-04-30 09:54 UTC
According to a code comment in the docs, "master" is optional:

![image](https://user-images.githubusercontent.com/89534395/235346946-27726388-ac97-463f-9ebc-52c90d88bf4e.png)

However, when trying to use master, e.g.
```
        self._top_geometry = ctk.CTkToplevel(master=self.ctk_control_panel)
        self._top_geometry.title(f'{widget_type} Widget Geometry')
```
The above code worked fine in the previous release of CustomTkinter, however now,
this exception is encountered:
```

    return self.func(*args)
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/ctk_button.py", line 553, in _clicked
    self._command()
  File "/home/clive/PycharmProjects/ctk5_theme_builder/ctk_theme_builder.py", line 992, in <lambda>
    command=lambda: self._edit_widget_geometry('Button'))
  File "/home/clive/PycharmProjects/ctk5_theme_builder/ctk_theme_builder.py", line 1124, in _edit_widget_geometry
    self._top_geometry = ctk.CTkToplevel(master=self.ctk_control_panel)
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/ctk_toplevel.py", line 39, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "/home/clive/PycharmProjects/ctk5_theme_builder/venv/lib/python3.8/site-packages/customtkinter/windows/widgets/utility/utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['master'] are not supported arguments. Look at the documentation for supported arguments.
```

**Comment by TomSchimansky** [comment] 2023-05-27 11:27
Duplicate of #1468

**Closed by TomSchimansky** 2023-05-27 11:27 UTC
