### ISSUE TITLE
.config(status="disables") that works in tkinter does not work in customtkinter

### ISSUE THREAD

**Issue by erolsavas19** [TomSchimansky/CustomTkinter#1535] opened 2023-04-29 22:23 UTC
#You can also check the example below.
#.config(state="disabled") customtkinter doesn't work either. It works when #using Tkinter. What method can I follow to solve this problem?
#
#--> entry_disabled.config(state= "disabled")
#-----------------------------------------------------

from tkinter import *
import customtkinter

window = customtkinter.CTk()
window.geometry("320x200")

d1 = StringVar()

# normal entry widget
entry=customtkinter.CTkEntry(window, textvariable=d1, width= 300)
entry.pack(pady=20)

# entry2=Entry(window, textvariable=d1, width= 300)
# entry2.pack(pady=20)

# disabled entry widget
entry_disabled=customtkinter.CTkEntry(window, textvariable=d1, width= 300)
entry_disabled.pack(pady=20)
entry_disabled.config(state= "disabled")

# entry_disabled2=Entry(window, textvariable=d1, width= 300)
# entry_disabled2.pack(pady=20)
# entry_disabled2.config(state= "disabled")

window.mainloop()

**Comment by avalon60** [comment] 2023-04-30 09:10
Have you tried:

`state=customtkinter.DISABLED`

**Comment by ElectricCandlelight** [comment] 2023-04-30 09:20
Duplicate of #1523 which was only asked 2 days ago.

If you read the error message, it tells you to use .configure 

When pasting in code please use a code block the "<>" just above the text box or using three backticks 
````
```Python
Example code block
```
````

**Closed** 2023-05-01 21:41 UTC

**Comment by erolsavas19** [comment] 2023-05-02 00:36
Bu çözümü zaten denedim.
Kodu test ederseniz, sorunun bu şekilde çözülmediğini göreceksiniz.
tkinter kullandığınızda sorun yok. customtkinter ile çalışmaz.

**Comment by erolsavas19** [comment] 2023-05-02 00:37
I already tried this solution.
If you test the code, you'll see that the problem is not fixed this way.
There is no problem when you use tkinter. It doesn't work with customtkinter.

**Comment by ElectricCandlelight** [comment] 2023-05-02 01:42
Use .configure(state="disabled") instead of .config

If it's still not working post an example.

**Comment by erolsavas19** [comment] 2023-05-02 02:00
.configure(state="disabled")

I tried the way you suggested and it worked.
Thank you very much for your help.
